### ISSUE TITLE
Various dependent python packages do not always install correctly using the documented script

### ISSUE THREAD

**Issue by ericrickydixon** [harris-helios/helios-sdk-python#2]
"pip install requests scikit-image retrying" - the documented script does not always install the packages listed correctly.  It might be good to inform the user to double check all packages get installed correctly using the example install script or to install them independently.  I had to install "requests" and "retrying" packages independently to get a good install.

**Comment by mab4058** [comment]
Were you running into errors when trying to import and use the SDK, or were package installations failing?  If you were receiving error messages could you send them to me?

**Comment by ericrickydixon** [comment]
I was getting package installs failing, but I was able to get them done individually.  The only module I’m having issue with is skimage.io (part of scikit-image).

As a sporadic Python developer, It would be nice to have more explanation of the sample code (examples.py):

**Comment by mab4058** [comment]
The "scikit-image" dependency was removed: a56076917bf3ffa473e0e795bf517555b08ba612
